version: "3"

services:
  web:
    build: "./server"
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - DB=mongodb://db:27017/RHS
  db:
    build: "./db"
    ports:
      - "27017:27017"